In [2]:
import numpy as np
import pandas as pd

In [10]:
pd.options.display.float_format = '{:.5f}'.format
bus_bts = pd.read_csv("bus_bts.csv")

In [11]:
bus_bts.head(20)

,user_card_id,bus_route_id,vhc_id,geton_date,geton_time,geton_station_code,geton_station_name,getoff_date,getoff_time,getoff_station_code,getoff_station_name,user_category,user_count
0,1010010127894129.00000,23000000,149793674,2019-09-10,06:34:45,360,노형오거리,2019-09-10,07:10:31,592.00000,화북초등학교,1,1
1,1010010101730356.00000,23000000,149793674,2019-09-10,06:34:58,360,노형오거리,2019-09-10,06:56:27,3273.00000,고산동산(광양방면),1,1
2,1019160032727943.00000,21420000,149793535,2019-09-10,07:19:07,2495,동광환승정류장4(제주방면),2019-09-10,07:40:29,431.00000,정존마을,4,1
3,1019150001770890.00000,21420000,149793512,2019-09-09,09:14:47,3282,대정환승정류장(대정읍사무소),2019-09-09,10:02:46,431.00000,정존마을,1,1
4,1010010097237127.00000,21420000,149793512,2019-09-09,09:28:53,2820,삼정지에듀,2019-09-09,10:21:37,2972.00000,제주국제공항(종점),4,1
5,1019150100594126.00000,31520000,149793453,2019-09-10,07:54:08,189,도호동,2019-09-10,08:07:09,3539.00000,탐라도서관,4,1
6,1019160029063302.00000,31520000,149793453,2019-09-10,08:11:47,476,한라중학교/부영아파트,2019-09-10,08:25:42,190.00000,제주중앙중학교,4,1
7,1010001585041526.00000,31520000,149793453,2019-09-10,08:25:47,190,제주중앙중학교,2019-09-10,08:33:45,74.00000,보건소,1,1
8,1010001733461832.00000,31520000,149793453,2019-09-10,08:30:22,74,보건소,2019-09-10,08:33:49,74.00000,보건소,1,1
9,1010010105509921.00000,31570000,149793528,2019-09-11,07:04:03,2495,동광환승정류장4(제주방면),2019-09-11,07:46:14,2970.00000,제주시외버스터미널(종점),1,1
10,1014140000065508.00000,31570000,149793528,2019-09-11,07:04:09,2495,동광환승정류장4(제주방면),2019-09-11,07:46:11,2970.00000,제주시외버스터미널(종점),6,1
11,1014140001113042.00000,31570000,149793528,2019-09-11,07:19:42,554,제주관광대학,2019-09-11,07:38:19,361.00000,남녕고등학교,6,1
12,1019160037054400.00000,31570000,149793528,2019-09-11,07:22:12,554,제주관광대학,2019-09-11,07:38:50,358.00000,한라병원,1,1
13,1019160033867607.00000,31570000,149793528,2019-09-11,07:22:14,554,제주관광대학,2019-09-11,07:35:11,360.00000,노형오거리,1,1
14,1019160000930669.00000,31350000,149793472,2019-09-10,07:57:23,124,아라주공아파트,2019-09-10,08:03:00,3279.00000,제주여자중고등학교(광양방면),4,1
15,1019150191692409.00000,31350000,149793472,2019-09-10,07:59:39,131,아라동주민센터,2019-09-10,08:03:10,3279.00000,제주여자중고등학교(광양방면),2,1
16,1019150188288153.00000,31350000,149793472,2019-09-10,07:59:41,131,아라동주민센터,2019-09-10,08:02:39,3279.00000,제주여자중고등학교(광양방면),4,1
17,1010010133973040.00000,31350000,149793472,2019-09-10,08:03:41,3279,제주여자중고등학교(광양방면),2019-09-10,08:04:41,3277.00000,제주중앙여자고등학교(광양방면),4,1
18,1019160028160679.00000,31350000,149793472,2019-09-10,08:25:39,291,천수동,2019-09-10,08:32:19,592.00000,화북초등학교,1,1
19,1019150183773860.00000,22530000,149793400,2019-09-11,07:51:16,1919,비석거리,2019-09-11,08:01:42,1869.00000,서귀포산업과학고등학교,4,1

In [12]:
bus_bts.isnull().sum()

user_card_id                0
bus_route_id                0
vhc_id                      0
geton_date                  0
geton_time                  0
geton_station_code          0
geton_station_name         49
getoff_date            895736
getoff_time            895736
getoff_station_code    895736
getoff_station_name    895775
user_category               0
user_count                  0
dtype: int64

In [9]:
len(bus_bts)

2409414

In [13]:
train = pd.read_csv("train.csv")

In [14]:
train.head(20)

,id,date,bus_route_id,in_out,station_code,station_name,latitude,longitude,6~7_ride,7~8_ride,...,9~10_ride,10~11_ride,11~12_ride,6~7_takeoff,7~8_takeoff,8~9_takeoff,9~10_takeoff,10~11_takeoff,11~12_takeoff,18~20_ride
0,0,2019-09-01,4270000,시외,344,제주썬호텔,33.48990,126.49373,0.00000,1.00000,...,5.00000,2.00000,6.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000
1,1,2019-09-01,4270000,시외,357,한라병원,33.48944,126.48508,1.00000,4.00000,...,2.00000,5.00000,6.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,5.00000
2,2,2019-09-01,4270000,시외,432,정존마을,33.48181,126.47352,1.00000,1.00000,...,2.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,2.00000
3,3,2019-09-01,4270000,시내,1579,제주국제공항(600번),33.50577,126.49252,0.00000,17.00000,...,26.00000,14.00000,16.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,53.00000
4,4,2019-09-01,4270000,시내,1646,중문관광단지입구,33.25579,126.41260,0.00000,0.00000,...,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000
5,5,2019-09-01,4270000,시내,1648,예래입구,33.25862,126.40442,0.00000,0.00000,...,0.00000,1.00000,0.00000,0.00000,0.00000,1.00000,0.00000,1.00000,0.00000,0.00000
6,6,2019-09-01,4270000,시외,1660,제주국제컨벤션센터중문대포해안주상절리대,33.24309,126.42472,0.00000,1.00000,...,0.00000,2.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1.00000,5.00000,3.00000
7,7,2019-09-01,4270000,시외,1666,창천리,33.26598,126.37082,1.00000,0.00000,...,0.00000,0.00000,0.00000,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000
8,8,2019-09-01,4270000,시외,1726,강정농협,33.23603,126.47827,0.00000,0.00000,...,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,1.00000,0.00000,2.00000
9,9,2019-09-01,4270000,시내,2008,서귀포항,33.23977,126.56450,0.00000,0.00000,...,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,2.00000,0.00000,2.00000,0.00000
10,10,2019-09-01,4270000,시외,2009,뉴경남호텔,33.24613,126.55957,0.00000,0.00000,...,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1.00000,4.00000,0.00000,0.00000
11,11,2019-09-01,4270000,시내,2013,신라호텔,33.24775,126.40793,0.00000,0.00000,...,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1.00000,1.00000,0.00000
12,12,2019-09-01,4270000,시외,2014,하얏트호텔,33.24511,126.40579,0.00000,0.00000,...,0.00000,0.00000,0.00000,2.00000,0.00000,0.00000,0.00000,1.00000,0.00000,1.00000
13,13,2019-09-01,4270000,시외,2094,한국콘도입구,33.25024,126.41022,0.00000,2.00000,...,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1.00000
14,14,2019-09-01,4270000,시외,2095,켄싱턴제주호텔입구,33.25037,126.40992,0.00000,0.00000,...,0.00000,0.00000,0.00000,0.00000,1.00000,1.00000,0.00000,1.00000,0.00000,0.00000
15,15,2019-09-01,4270000,시외,2114,스위트호텔,33.24904,126.40767,0.00000,0.00000,...,0.00000,0.00000,4.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,4.00000
16,16,2019-09-01,4270000,시내,2494,동광환승정류장5(서귀방면),33.30958,126.34083,0.00000,0.00000,...,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,3.00000,2.00000,6.00000
17,17,2019-09-01,4270000,시외,2697,대포항,33.23974,126.43773,0.00000,0.00000,...,0.00000,0.00000,0.00000,0.00000,1.00000,0.00000,0.00000,0.00000,0.00000,0.00000
18,18,2019-09-01,4270000,시외,2699,약천사,33.24289,126.45084,0.00000,0.00000,...,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1.00000,0.00000,0.00000
19,19,2019-09-01,4270000,시내,2843,중문관광단지여미지식물원입구,33.25214,126.41268,1.00000,0.00000,...,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,7.00000,3.00000,0.00000

In [15]:
train.isnull().sum()

id               0
date             0
bus_route_id     0
in_out           0
station_code     0
station_name     0
latitude         0
longitude        0
6~7_ride         0
7~8_ride         0
8~9_ride         0
9~10_ride        0
10~11_ride       0
11~12_ride       0
6~7_takeoff      0
7~8_takeoff      0
8~9_takeoff      0
9~10_takeoff     0
10~11_takeoff    0
11~12_takeoff    0
18~20_ride       0
dtype: int64

In [4]:
submission = pd.read_csv("submission_sample.csv")

In [5]:
submission.head()

       id  18~20_ride
0  415423           0
1  415424           0
2  415425           0
3  415426           0
4  415427           0